### ISSUE TITLE
Calling nil on some linux/emacs installs

### ISSUE THREAD

**Issue by mitchty** [myuhe/smartrep.el#14]
So, I didn't debug this too hard, but its showing up on mavericks with emacs 24.3 as well now.

https://github.com/mitchty/smartrep.el/commit/a002cc88c4d867cba0e68c694e2d9b44d18f6a29

But this bit:
```elisp
 (let ((cell (or (memq 'mode-line-position mode-line-format) 
      (memq 'mode-line-buffer-identification mode-line-format))) 
        (newcdr 'smartrep-mode-line-string))
```

Will evaluate to nil, thus causing the setcdr to fail because cell is nil.

```elisp
     (setcdr cell (cons newcdr (cdr cell)))))
```

I just switched:
```elisp
  (unless (member newcdr mode-line-format) 
```

To this (hacky but it seems to work just fine for the past 2 months:
```elisp
(unless (eq (member newcdr mode-line-format) nil)
```

Without this plugins like diff-hl-mode fail to work. Not sure if anyone else has/is run into this issue.

I can provide other output/information if you want but getting this fix in would be nice. Do you want a merge request if this "fix" is acceptable or would there be some other way you'd like to get this fix in?

**Comment by myeffort** [comment]
Same problem, emacs 25.0.50.1

**Comment by Silex** [comment]
I think I referenced the same bug, with reproducable steps.
